fix: change cicd structure

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,39 +1,126 @@
+#name: EnergyTajo CI/CD
+#
+#on:
+#  push:
+#    branches: ["main"]
+#  pull_request:
+#    branches: ["main"]
+#
+#permissions:
+#  contents: write
+#  packages: write
+#  actions: write
+#
+#jobs:
+#  CI:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: get code from remote repository
+#        uses: actions/checkout@v4
+#        with:
+#          token: ${{ secrets.SECRET_TOKEN }}
+#          submodules: true
+#
+#      - name: setup jdk 17
+#        uses: actions/setup-java@v4
+#        with:
+#          java-version: '17'
+#          distribution: 'temurin'
+#
+#      - name: Grant execute permission for gradlew
+#        run: chmod +x gradlew
+#
+#      - name: Build with Gradle
+#        run: ./gradlew clean build
+#
+#      - name: Copy build file to home directory
+#        uses: appleboy/scp-action@master
+#        with:
+#          host: ${{ secrets.SSH_HOST }}
+#          username: ${{ secrets.SSH_USERNAME }}
+#          key: ${{ secrets.SSH_PRIVATE_KEY }}
+#          port: ${{ secrets.SSH_PORT }}
+#          source: "build/libs/*.jar"
+#          target: "~/source"
+#          rm: true
+#
+#
+#  CD:
+#    needs: CI
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Deploy
+#        uses: appleboy/ssh-action@master
+#        with:
+#          host: ${{ secrets.SSH_HOST }}
+#          username: ${{ secrets.SSH_USERNAME }}
+#          key: ${{ secrets.SSH_PRIVATE_KEY }}
+#          port: ${{ secrets.SSH_PORT }}
+#          script: |
+#            echo "#### Enter the deployment section ####"
+#
+#            FILE_NAME=$(find ~/source/build/libs -maxdepth 1 -name "*.jar" | head -n 1)
+#            PID=$(ps -ef | grep 'java -jar' | grep -v "grep" | awk '{print $2}')
+#            LOG_DIR=~/source/build
+#            LOG_FILE=$LOG_DIR/logfile_$(date +"%Y%m%d_%H%M%S").log
+#
+#            mkdir -p $LOG_DIR
+#
+#            if [ -z "$PID" ]; then
+#              echo "#### NO RUNNING PROCESS ####"
+#            else
+#              echo "#### KILLING PROCESS $PID ####"
+#              kill $PID
+#            fi
+#
+#            echo "#### LINKING $FILE_NAME to ~/EnergyTajo.jar ####"
+#            ln -sf $FILE_NAME ~/EnergyTajo.jar
+#
+#            echo "#### RUNNING JAR ####"
+#            nohup java -jar ~/EnergyTajo.jar > $LOG_FILE 2>&1 &
+#
+#      - name: Verify HTTPS Deployment
+#        run: |
+#          echo "#### Checking HTTPS response ####"
+#          sleep 10
+#          curl -I https://energytajo.site || echo "#### HTTPS check failed ####"
+
+
+
+
+
+
+
+
+
 name: EnergyTajo CI/CD
 
 on:
   push:
-    branches: ["main"]
+    branches: [ "main" ]
   pull_request:
-    branches: ["main"]
-
-permissions:
-  contents: write
-  packages: write
-  actions: write
+    branches: [ "main" ]
 
 jobs:
   CI:
     runs-on: ubuntu-latest
     steps:
-      - name: get code from remote repository
+      - name: Checkout Code
         uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.SECRET_TOKEN }}
-          submodules: true
 
-      - name: setup jdk 17
+      - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Grant execute permission for gradlew
+      - name: Grant Permission
         run: chmod +x gradlew
 
-      - name: Build with Gradle
+      - name: Build
         run: ./gradlew clean build
 
-      - name: Copy build file to home directory
+      - name: Upload JAR with SCP
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.SSH_HOST }}
@@ -41,46 +128,4 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: ${{ secrets.SSH_PORT }}
           source: "build/libs/*.jar"
-          target: "~/source"
-          rm: true
-
-
-  CD:
-    needs: CI
-    runs-on: ubuntu-latest
-    steps:
-      - name: Deploy
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: ${{ secrets.SSH_PORT }}
-          script: |
-            echo "#### Enter the deployment section ####"
-
-            FILE_NAME=$(find ~/source/build/libs -maxdepth 1 -name "*.jar" | head -n 1)
-            PID=$(ps -ef | grep 'java -jar' | grep -v "grep" | awk '{print $2}')
-            LOG_DIR=~/source/build
-            LOG_FILE=$LOG_DIR/logfile_$(date +"%Y%m%d_%H%M%S").log
-
-            mkdir -p $LOG_DIR
-
-            if [ -z "$PID" ]; then
-              echo "#### NO RUNNING PROCESS ####"
-            else
-              echo "#### KILLING PROCESS $PID ####"
-              kill $PID
-            fi
-
-            echo "#### LINKING $FILE_NAME to ~/EnergyTajo.jar ####"
-            ln -sf $FILE_NAME ~/EnergyTajo.jar
-
-            echo "#### RUNNING JAR ####"
-            nohup java -jar ~/EnergyTajo.jar > $LOG_FILE 2>&1 &
-
-      - name: Verify HTTPS Deployment
-        run: |
-          echo "#### Checking HTTPS response ####"
-          sleep 10
-          curl -I https://energytajo.site || echo "#### HTTPS check failed ####"
+          target: "~/source/build/libs"
